### ISSUE TITLE
Plugin doesn't load if closed while referencing a server which is "bad" or collection not parsable.

### ISSUE THREAD

**Issue by MattWardle** [lutraconsulting/qgis-plugin-edr#29]
Need option to clear server from %APPDATA%\Roaming\profiles\default\QGIS\QGIS3 in case there is an issue with it, i.e. it is down, or the collection it is referring to is malformed.
Otherwise at the moment the plugin crashes.

**Comment by ldebek** [comment]
Improvements available in plugin version >= 0.8.0.
