### ISSUE TITLE
QGIS Plugin Difficult To Use On Laptop Monitor

### ISSUE THREAD

**Issue by Gugym** [lutraconsulting/qgis-plugin-edr#37]
When using the edr plugin on the laptop monitor it is not possible to see the whole screen.

The screenshot shows the view which does not allow the user to click on the buttons at the bottom of the plugin easily (if at all).
<img width="960" alt="PluginExtent" src="https://github.com/lutraconsulting/qgis-plugin-edr/assets/4614980/8402028b-998f-4c12-af54-1d95eff61903">

It is also very difficult to re-size the plugin in these circumstances.

**Comment by ldebek** [comment]
@Gugym This is usually caused by a scaling applied in the Windows display properites. Please try out settting you display scaling to 100%. If it won't help then we can apply some fixes on a code level, but it will take some time to find most flexible settings.

**Comment by ldebek** [comment]
Improvements available in plugin version >= 0.8.0.
