### ISSUE TITLE
The Position Query Does Not Allow User To Select A Point On Map

### ISSUE THREAD

**Issue by Gugym** [lutraconsulting/qgis-plugin-edr#45]
Steps to reproduce : Version 0.8.0 of the QGIS Plugin.

Open the EDR interface and choose the following service:

<img width="400" alt="image" src="https://github.com/lutraconsulting/qgis-plugin-edr/assets/4614980/43ad0c3a-aa23-4b3e-ad76-ca0a8a00a8d1">

When setting the spatial extent, the user clicks on the map and no point is selected. The EDR interface has closed and will need to be re-opened.

Expected behaviour: 
User can click on  the map to define a position (point location) before it is returned to the EDR interface to build the position request.

**Comment by ldebek** [comment]
Fixed in version 0.9.0
