### ISSUE TITLE
Restrict the Query Types To Those Supported By The Plugin

### ISSUE THREAD

**Issue by Gugym** [lutraconsulting/qgis-plugin-edr#46]
For the following service the user should not be able to see the trajectory query as it is not supported by version 0.8.0 of the plugin:

<img width="402" alt="image" src="https://github.com/lutraconsulting/qgis-plugin-edr/assets/4614980/a19200f5-8306-4079-ab2b-ac382eebc7d0">

Expected behaviour: the user should not be able to see the trajectory query here as it is not supported.

**Comment by ldebek** [comment]
Fixed in version 0.9.0
