### ISSUE TITLE
When Not Defining A Point On A Radius Query The User Is Shown A Python Window

### ISSUE THREAD

**Issue by Gugym** [lutraconsulting/qgis-plugin-edr#47]
Steps to reproduce in version 0.8.0:

Define a radius query:
<img width="400" alt="image" src="https://github.com/lutraconsulting/qgis-plugin-edr/assets/4614980/84cea264-0318-4192-a54a-3980784590f4">
Click set spatial extent: when the dialogue is open click on OK without setting a radius centre point. The user is shown this error:
<img width="558" alt="image" src="https://github.com/lutraconsulting/qgis-plugin-edr/assets/4614980/1ea220c5-6cb7-423b-a6c4-60d95de6820b">
Expected behaviour: The user should be shown an error message saying that they have not set the radius centre point from the map.

**Comment by ldebek** [comment]
Fixed in version 0.9.0
